import * as fs from 'fs';

async function run() {
  const formatDollar = (cents: number) => `$${(Math.abs(cents) / 100).toLocaleString('en-US', {minimumFractionDigits: 2})}`;
  
  const inLoop = 13;
  const handler = 21;
  const scheduled = 16;
  const batch = 3;
  const direct = 1;

  let markdown = `## 📊 CloudGauge Cost Impact Analysis\n\n`;
  markdown += `### 💰 ESTIMATED MONTHLY COST DELTA\n`;
  markdown += `# **+$19,613.80/mo**\n`;
  markdown += `*Detected 32 cost-impacting pattern(s) across 10 service(s).*\n\n`;
  markdown += `---\n\n`;
  markdown += `### ⚙️ EXECUTION CONTEXT IMPACT\n`;
  markdown += `| 🔄 In Loop | 🌐 Handler | ⏱️ Scheduled | 📦 Batch | 📌 Direct |\n`;
  markdown += `|:---:|:---:|:---:|:---:|:---:|\n`;
  markdown += `| **${inLoop}**<br>^(High Impact)^ | **${handler}**<br>^(Per Request)^ | **${scheduled}**<br>^(Recurring)^ | **${batch}**<br>^(Concurrent)^ | **${direct}**<br>^(Baseline)^ |\n\n`;
  markdown += `---\n\n`;

  markdown += `### 📋 COST BREAKDOWN\n`;
  markdown += `| Service / Model | Detected Code Snippet | Monthly Delta |\n`;
  markdown += `|:---|:---|---:|\n`;
  
  markdown += `| 🤖 **OpenAI** \`gpt-4o\` | \`const response = await openai.chat.completions.create(...)\` | **+$87,500.00/mo** |\n`;
  markdown += `| 🌐 **API Gateway** | \`app.post('/generate', async (req, res) => {...})\` | **+$17.50/mo** |\n`;
  markdown += `| ✨ **Anthropic** \`claude-3-sonnet\` | \`const result = await client.messages.create(...)\` | **+$925.00/mo** |\n`;

  markdown += `\n\n> ⚡ *Automatically generated by CloudGauge PR Analyzer.*`;

  fs.writeFileSync('PR_COMMENT_PREVIEW.md', markdown);
  console.log(`✅ Analysis complete! Wrote output to PR_COMMENT_PREVIEW.md`);
}

run().catch(console.error);
